spring:
  application:
    name: inventaire_produits_api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/inventaire_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true