spring:
  application:
    name: inventaire_produits_api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/inventaire_db
    username: hels
    password: hels
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html